name: Steckbrief
version: '${project.version}'
main: de.redfox.steckbrief.Steckbrief
api-version: 1.18
authors: [ Kevin, UnleqitQ ]
depend:
  - HeadDatabase
  - HeadDisplays
  - PlaceholderAPI

commands:
  roleplay:
    aliases:
      - rp

